apiVersion: apps/v1
kind: Deployment
metadata:
  name: semaphore
spec:
  selector:
    matchLabels:
      app: semaphore
  template:
    metadata:
      labels:
        app: semaphore
    spec:
      containers:
      - name: semaphore
        image: ubuntu:16.04
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "semaphoreDB!"
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        ports:
          - containerPort: 3000
      - name: mariadb
        image: mariadb:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "semaphoreDB!"
        ports:
          - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: semaphore-service
spec:
  type: NodePort
  selector:
    app: semaphore
  ports:
  - port: 3000
    targetPort: 3000